[[plugins]]
repo = 'Shougo/dein.vim'

repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

 Golang
[[plugins]]
repo = 'fatih/vim-go'


# Color schemes
[[plugins]]
repo = 'raphamorim/lucario' #colorscheme lucario

[[plugins]]
repo = 'jdkanani/vim-material-theme' #olorscheme material-theme
